import { Quest, QuestCategory, QuestStatus } from './types';

export const LEVEL_TITLES = [
  "Novice Explorer",
  "Curious Wanderer",
  "Seasoned Adventurer",
  "Bold Voyager",
  "Odyssey Master",
  "Life Architect"
];

// Pre-categorized list based on the user's input
export const INITIAL_QUESTS: Quest[] = [
  { id: 1, title: "Life documentation", category: QuestCategory.Solo, status: QuestStatus.Pending, isBold: false },
  { id: 2, title: "Trying a sport I never played before", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: true },
  { id: 3, title: "Host a dinner party with close friends", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: false },
  { id: 4, title: "Learn a short dance choreo", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: false },
  { id: 5, title: "Bake a cake", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: false },
  { id: 6, title: "DIY creative from Pinterest", category: QuestCategory.Creative, status: QuestStatus.Pending, isBold: false },
  { id: 7, title: "Take food, go for a picnic", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: false },
  { id: 8, title: "A new instrument (drums)", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: false },
  { id: 9, title: "Unplanned trip to somewhere near", category: QuestCategory.Adventure, status: QuestStatus.Pending, month: 'Jan', isBold: false },
  { id: 10, title: "Dress up and go somewhere that feels cinematic", category: QuestCategory.Adventure, status: QuestStatus.Pending, month: 'Feb', isBold: false },
  { id: 11, title: "Attend a skill workshop and learn it", category: QuestCategory.Skill, status: QuestStatus.Pending, month: 'Mar', isBold: false },
  { id: 12, title: "Get up early to watch the sun rise from the dark", category: QuestCategory.Solo, status: QuestStatus.Pending, month: 'May', isBold: false },
  { id: 13, title: "Say yes for 24 hours", category: QuestCategory.Adventure, status: QuestStatus.Pending, month: 'Jun', isBold: true },
  { id: 14, title: "Attend an event alone", category: QuestCategory.Solo, status: QuestStatus.Pending, month: 'Jul', isBold: true },
  { id: 15, title: "Sleep somewhere that isn’t my home", category: QuestCategory.Adventure, status: QuestStatus.Pending, month: 'Aug', isBold: false },
  { id: 16, title: "Do something with a stage or spotlight", category: QuestCategory.Adventure, status: QuestStatus.Pending, month: 'Oct', isBold: true },
  { id: 17, title: "Volunteer for something for a day", category: QuestCategory.Social, status: QuestStatus.Pending, month: 'Nov', isBold: false },
  { id: 18, title: "Give off little awards to the people ik", category: QuestCategory.Social, status: QuestStatus.Pending, month: 'Dec', isBold: false },
  { id: 19, title: "Give someone flowers", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: false },
  { id: 20, title: "Letter to self", category: QuestCategory.Solo, status: QuestStatus.Pending, isBold: false },
  { id: 21, title: "Colour coded photography day", category: QuestCategory.Creative, status: QuestStatus.Pending, isBold: false },
  { id: 22, title: "Finish a book in a day", category: QuestCategory.Solo, status: QuestStatus.Pending, isBold: false },
  { id: 23, title: "Make a small diary of poems", category: QuestCategory.Creative, status: QuestStatus.Pending, isBold: false },
  { id: 24, title: "Try new recipes", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: false },
  { id: 25, title: "Earn 1000$ from a hobby", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: true },
  { id: 26, title: "Record a podcast", category: QuestCategory.Creative, status: QuestStatus.Pending, isBold: true },
  { id: 27, title: "Visit art gallery", category: QuestCategory.Adventure, status: QuestStatus.Pending, isBold: false },
  { id: 28, title: "Art date", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: false },
  { id: 29, title: "Room restyling", category: QuestCategory.Creative, status: QuestStatus.Pending, isBold: false },
  { id: 30, title: "Go for a walk with no music and observe, note on a diary", category: QuestCategory.Solo, status: QuestStatus.Pending, isBold: false },
  { id: 31, title: "Go to a standup comedy show", category: QuestCategory.Adventure, status: QuestStatus.Pending, isBold: false },
  { id: 32, title: "Make a business and pitch it to people", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: true },
  { id: 33, title: "Send a bold email asking for an opportunity im scared of", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: true },
  { id: 34, title: "Try calligraphy", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: false },
  { id: 35, title: "Bike rides", category: QuestCategory.Adventure, status: QuestStatus.Pending, isBold: false },
  { id: 36, title: "Draw a comic for fun", category: QuestCategory.Creative, status: QuestStatus.Pending, isBold: false },
  { id: 37, title: "Let my friends design a card for a day", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: false },
  { id: 38, title: "Build a second brain with notion/obsidian", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: false },
  { id: 39, title: "Perfume trial date", category: QuestCategory.Solo, status: QuestStatus.Pending, isBold: false },
  { id: 40, title: "Start a YT channel", category: QuestCategory.Creative, status: QuestStatus.Pending, isBold: true },
  { id: 41, title: "Pay for a stranger at grocery", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: true },
  { id: 42, title: "Make a short film", category: QuestCategory.Creative, status: QuestStatus.Pending, isBold: false },
  { id: 43, title: "Make a stranger pick outfit for you", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: true },
  { id: 44, title: "Go karting", category: QuestCategory.Adventure, status: QuestStatus.Pending, isBold: false },
  { id: 45, title: "Talk to stranger to hear a different perspective", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: true },
  { id: 46, title: "Delete 1 app", category: QuestCategory.Solo, status: QuestStatus.Pending, isBold: false },
  { id: 47, title: "Bottle flip challenge", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: false },
  { id: 48, title: "Make a reel with a friend", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: false },
  { id: 49, title: "Ask a stranger elderly about something of their life", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: true },
  { id: 50, title: "Go to a cafe and try their cashier/server recommendations", category: QuestCategory.Adventure, status: QuestStatus.Pending, isBold: false },
  { id: 51, title: "Clean my room", category: QuestCategory.Solo, status: QuestStatus.Pending, isBold: false },
  { id: 52, title: "Solve a murder mystery", category: QuestCategory.Adventure, status: QuestStatus.Pending, isBold: false },
  { id: 53, title: "Plant a tree", category: QuestCategory.Adventure, status: QuestStatus.Pending, isBold: false },
  { id: 54, title: "Take psychological tests", category: QuestCategory.Solo, status: QuestStatus.Pending, isBold: false },
  { id: 55, title: "Go see a LDR friend", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: false },
  { id: 56, title: "Learn a magic trick", category: QuestCategory.Skill, status: QuestStatus.Pending, isBold: false },
  { id: 57, title: "Colour coded food prep for a day", category: QuestCategory.Creative, status: QuestStatus.Pending, isBold: false },
  { id: 58, title: "Only fruit diet a day", category: QuestCategory.Solo, status: QuestStatus.Pending, isBold: false },
  { id: 59, title: "Rainy Day puddle jumping", category: QuestCategory.Adventure, status: QuestStatus.Pending, isBold: false },
  { id: 60, title: "Coffee Shop Crawl: Visit 3 shops and rank vibe", category: QuestCategory.Adventure, status: QuestStatus.Pending, isBold: false },
  { id: 61, title: "Send a 30-second voice note to 5 people", category: QuestCategory.Social, status: QuestStatus.Pending, isBold: true },
];